# Generated by Django 3.2.6 on 2021-08-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_de_nacimineto', models.DateField()),
                ('correo', models.EmailField(max_length=200)),
                ('telefono', models.CharField(max_length=10)),
                ('fecha_ingrso', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
